name: CI Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: List directory contents
        run: ls -R

      - name: Build TypeScript
        run: npm run build

      - name: Run migrations
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
        run: npm run migration:run

      - name: Run tests
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
        run: npm test





# name: CI Backend

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:15
#         env:
#           POSTGRES_USER: test_user
#           POSTGRES_PASSWORD: test_password
#           POSTGRES_DB: test_db
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd "pg_isready -U test_user"
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm install

#       - name: Build TypeScript
#         run: npm run build

#       - name: Run migrations
#         env:
#           DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
#         run: npm run migration:run

#       - name: Run tests
#         env:
#           DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db

#         run: npm test
